import Head from 'next/head'
import Game from '../components/Game/Game.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whack-a-clive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Game />
    </div>
  )
}
