import Head from 'next/head'
import Game from '../components/Game/Game.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whack-a-clive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.sandbox.google.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,700,1,0" />
      </Head>
      <Game />
    </div>
  )
}
